// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaveEntityFramework;

namespace SaveEntityFramework.Migrations
{
    [DbContext(typeof(SavesDbContext))]
    [Migration("20221229073357_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("SaveEntityFramework.DTOs.SaveDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationDisplay")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaveName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDisplay")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeDisplay")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Saves");
                });
#pragma warning restore 612, 618
        }
    }
}
